version: "3.7"
networks:
  network-service:
    driver: bridge
    name: internal-network
    ipam:
      config:
        - subnet: 10.10.0.0/16

services:
  postgres:
    container_name: postgres_container
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: baseapplication
    ports:
      - "7000:5432"
    volumes:
      - ./data:/data/
    networks:
      network-service:
        ipv4_address: 10.10.0.10
    
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "7001:80"
    depends_on:
      - postgres
    volumes:
      - ./data/:/data/
      - ./postgres-backup:/var/lib/postgresql/backups
    networks:
      network-service:
        ipv4_address: 10.10.0.11
